# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='company_mgm.Company'),
        ),
    ]
