# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=255)),
                ('token_type', models.CharField(choices=[('card', 'RFID Card'), ('keychain', 'RFID Keychain')], default='card', max_length=25)),
                ('token_status', models.CharField(choices=[('assigned', 'Assigned'), ('lost', 'Lost'), ('unassigned', 'Unassigned')], default='unassigned', max_length=25)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
