# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_mgm', '0003_auto_20161114_2201'),
        ('card_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfid',
            options={'verbose_name': 'RFID', 'verbose_name_plural': 'RFIDs'},
        ),
        migrations.AddField(
            model_name='rfid',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid', to='company_mgm.Company'),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
