# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
