# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_mgm', '0002_auto_20161115_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='api_password',
        ),
    ]
