# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_mgm', '0003_remove_device_api_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('work_in', 'Work in'), ('work_out', 'Work out'), ('holiday_in', 'Holiday in'), ('holiday_out', 'Holiday out'), ('break_in', 'Break in'), ('break_out', 'Break out'), ('access', 'Access')], default='access', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='device_mgm.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
