# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'verbose_name_plural': 'Attendance entries'},
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='access_result',
            field=models.CharField(blank=True, choices=[('access_denied', 'Access Denied'), ('access_granted', 'Access Granted')], default=None, max_length=25, null=True),
        ),
    ]
