# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_mgm', '0003_auto_20161114_2201'),
        ('user_mgm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_mgm.Company'),
        ),
    ]
